@file:Suppress("SpellCheckingInspection")

package jp.sadashi.narou.reader.novel.infra.api.response

data class NovelSearchResponse(
    val ncode: String?,
    val title: String?,
    val writer: String?,
    val story: String?,
    val all_point: Int?,
    val review_cnt: Int?,
    val fav_novel_cnt: Int?,
    val novelupdated_at: String?,
    val allcount: Int?,
    val all_hyoka_cnt: Int?,
    val biggenre: Int?,
    val end: Int?,
    val general_all_no: Int?,
    val general_firstup: String?,
    val general_lastup: String?,
    val genre: Int?,
    val gensaku: String?,
    val global_point: Int?,
    val isbl: Int?,
    val isgl: Int?,
    val isr15: Int?,
    val isstop: Int?,
    val istenni: Int?,
    val istensei: Int?,
    val iszankoku: Int?,
    val kaiwaritu: Int?,
    val keyword: String?,
    val length: Int?,
    val novel_type: Int?,
    val pc_or_k: Int?,
    val sasie_cnt: Int?,
    val time: Int?,
    val updated_at: String?,
    val userid: Int?
)